package scripts.abc2;

/**
 * Created by frank on 4-7-2017.
 */

import org.tribot.api.General;
import org.tribot.api2007.Player;
import org.tribot.api2007.types.RSTile;

import javax.swing.*;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.Arrays;

/**
 *
 * @author frank
 */
public class Ui extends javax.swing.JFrame {

    /**
     * Creates new form Ui
     */
    public Ui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        fishingSpotLabel = new javax.swing.JLabel();
        spotIdText = new javax.swing.JTextField();
        fishGearLabel = new javax.swing.JLabel();
        fishGearIds = new javax.swing.JTextField();
        actionLabel = new javax.swing.JLabel();
        actionText = new javax.swing.JTextField();
        powerFishRadioButton = new javax.swing.JRadioButton();
        bankRadioButton = new javax.swing.JRadioButton();
        bankTileLabel = new javax.swing.JLabel();
        bankTileText = new javax.swing.JTextField();
        fishTileLabel = new javax.swing.JLabel();
        fishTileText = new javax.swing.JTextField();
        bankTileButton = new javax.swing.JButton();
        fishTileButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();


        buttonGroup1.add(powerFishRadioButton);
        buttonGroup1.add(bankRadioButton);
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Multifisher v2");

        fishingSpotLabel.setText("Fishing spot Ids: ");

        spotIdText.setText("1337,1338");

        fishGearLabel.setText("Fishing gear Ids:");

        fishGearIds.setText("303,304,306");

        actionLabel.setText("Action:");

        actionText.setText("Net");

        powerFishRadioButton.setText("Powerfishing");

        bankRadioButton.setSelected(true);
        bankRadioButton.setText("Banking");

        bankTileLabel.setText("Bank Tile:");

        bankTileText.setText("1,1,1");

        fishTileLabel.setText("Fish Tile:");

        fishTileText.setText("1,1,1");

        bankTileButton.setText("Set current tile");
        bankTileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankTileButtonActionPerformed(evt);
            }
        });

        fishTileButton.setText("Set current tile");
        fishTileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fishTileButtonActionPerformed(evt);
            }
        });

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(fishingSpotLabel)
                                                                                        .addComponent(actionLabel))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(spotIdText)
                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addComponent(actionText, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(fishGearLabel)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(fishGearIds)))))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(powerFishRadioButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(bankRadioButton)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(bankTileLabel)
                                                                        .addComponent(fishTileLabel))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(fishTileText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(fishTileButton))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(bankTileText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(bankTileButton)))))))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fishingSpotLabel)
                                        .addComponent(spotIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(actionLabel)
                                        .addComponent(actionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fishGearIds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fishGearLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(powerFishRadioButton)
                                        .addComponent(bankRadioButton))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bankTileButton)
                                        .addComponent(bankTileLabel)
                                        .addComponent(bankTileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fishTileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fishTileButton)
                                        .addComponent(fishTileLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 355, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 223, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    private void bankTileButtonActionPerformed(java.awt.event.ActionEvent evt) {
        RSTile tile = Player.getPosition();
        bankTileText.setText(tile.getX()+","+tile.getY()+","+tile.getPlane());
    }

    private void fishTileButtonActionPerformed(java.awt.event.ActionEvent evt) {
        RSTile tile = Player.getPosition();
        fishTileText.setText(tile.getX()+","+tile.getY()+","+tile.getPlane());
    }
    public boolean active = true;
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {
        saveSettings();
        try{
            Variables.ACTION = actionText.getText();
            String[] text;
            if(bankTileText.getText().length() > 0){
                text = bankTileText.getText().split(",");
                Variables.BANK_TILE = new RSTile(Integer.parseInt(text[0]), Integer.parseInt(text[1]), Integer.parseInt(text[2]));
            } else
                Variables.CUSTOM_BANK = false;

            text = fishTileText.getText().split(",");
            Variables.FISH_TILE = new RSTile(Integer.parseInt(text[0]), Integer.parseInt(text[1]), Integer.parseInt(text[2]));
            Variables.FISHING_GEAR_IDS = Arrays.stream(fishGearIds.getText().split(",")).mapToInt(Integer::parseInt).toArray();
            Variables.FISHING_SPOT_IDS = Arrays.stream(spotIdText.getText().split(",")).mapToInt(Integer::parseInt).toArray();
            Variables.IS_POWERFISHING = powerFishRadioButton.isSelected();
        }catch(Exception e){
            General.println("wrong user input.");
            e.printStackTrace();
        }

        active = false;
        this.setVisible(false);
    }

    private void saveSettings(){
        try{
            Variables.prop.clear();
            Variables.prop.put("spotIdText", spotIdText.getText());
            Variables.prop.put("actionText", actionText.getText());
            Variables.prop.put("fishGearIds", fishGearIds.getText());
            Variables.prop.put("powerFishRadioButton", String.valueOf(powerFishRadioButton.isSelected()));
            Variables.prop.put("bankRadioButton", String.valueOf(bankRadioButton.isSelected()));
            Variables.prop.put("bankTileText", bankTileText.getText());
            Variables.prop.put("fishTileText", fishTileText.getText());
            Variables.prop.store(new FileOutputStream(Variables.path), "GUI Settings");
        } catch (Exception e){
            e.printStackTrace();
        }
    }

    public void loadSettings(){
        try{
            if(!Variables.path.exists())
                Variables.path.createNewFile();
            Variables.prop.load(new FileInputStream(Variables.path));
            String[] textNames = {"spotIdText","actionText","fishGearIds","bankTileText","fishTileText"};
            JTextField[] textFields = {spotIdText,actionText,fishGearIds,bankTileText,fishTileText};
            for(int i = 0; i < textNames.length; i++){
                String value = Variables.prop.getProperty(textNames[i]);
                textFields[i].setText(value);
            }

            /*String[] radioButtons = {"powerFishRadioButton","bankRadioButton"};
            JRadioButton[] buttons = {powerFishRadioButton,bankRadioButton};
            for(int i = 0; i < radioButtons.length; i++){
                String value = Variables.prop.getProperty(radioButtons[i]);
                buttons[i].setEnabled(Boolean.valueOf(value));
            } */

        }catch (Exception e){
            General.println("loading failed");
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel actionLabel;
    private javax.swing.JTextField actionText;
    private javax.swing.JRadioButton bankRadioButton;
    private javax.swing.JButton bankTileButton;
    private javax.swing.JLabel bankTileLabel;
    private javax.swing.JTextField bankTileText;
    private javax.swing.JTextField fishGearIds;
    private javax.swing.JLabel fishGearLabel;
    private javax.swing.JButton fishTileButton;
    private javax.swing.JLabel fishTileLabel;
    private javax.swing.JTextField fishTileText;
    private javax.swing.JLabel fishingSpotLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton powerFishRadioButton;
    private javax.swing.JTextField spotIdText;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration                   
}
